// NOTE: this is not accurate at ALL gng
const getDay365 = () => {
    const date = new Date();
    const month = date.getMonth(); // january = 0
    const day = date.getDay(); // 1st = 1
    return (month * 30) + day;
};

const items = [
    "Sparkling Diamonds",
    "Golden Sunsets",
    "Vibrant Rainbows",
    "Silent Libraries",
    "Morning Coffee",
    "Ocean Waves",
    "Midnight Skies",
    "Freshly Baked",
    "Soft Petals",
    "Warm Fireplaces",
    "Colorful Parrots",
    "Starry Nights",
    "Gentle Whispers",
    "Crystal Caves",
    "Lush Greenery",
    "Sweet Serenades",
    "Sunset Hues",
    "Snowflakes Dance",
    "Freshly Cut Grass",
    "Lavender Dreams",
    "Morning Dew",
    "Glittering Gems",
    "Ocean Tides",
    "Moonlit Walks",
    "Golden Memories",
    "Whimsical Woodland",
    "Icy Cliffs",
    "Vibrant Markets",
    "Sparkling Fountains",
    "Distant Thunder",
    "Soft Blankets",
    "Majestic Mountains",
    "Tranquil Lakes",
    "Morning Singsongs",
    "Frosty Mornings",
    "Glowing Embers",
    "Hidden Waterfalls",
    "Colorful Skies",
    "Gentle Streams",
    "Midnight Feasts",
    "Lavender Fields",
    "Sparkling Pools",
    "Sunset Beaches",
    "Freshly Fallen Snow",
    "Tranquil Forests",
    "Morning Chirps",
    "Ocean Breezes",
    "Golden Light",
    "Silent Nights",
    "Whimsical Dreams",
    "Shimmering Mirrors",
    "Midnight Skaters",
    "Freshly Cut Flowers",
    "Gentle Rains",
    "Starry Showers",
    "Sparkling Streams",
    "Vibrant Fountains",
    "Ocean Currents",
    "Lush Canopies",
    "Moonlit Dances",
    "Warm Summer Nights",
    "Whimsical Clocks",
    "Icy Mornings",
    "Freshly Baked Cookies",
    "Colorful Kites",
    "Majestic Castles",
    "Tranquil Meadows",
    "Morning Sunrises",
    "Golden Honey",
    "Sparkling Crystals",
    "Glowing Lamps",
    "Midnight Feasts",
    "Vibrant Markets",
    "Silent Libraries",
    "Freshly Picked Fruits",
    "Starry Twinkles",
    "Whimsical Toys",
    "Ocean Waves Crash",
    "Soft Blankets Folded",
    "Lavender Dreams Unfold",
    "Morning Dew Glistens",
    "Crystal Caves Sparkle",
    "Golden Sunbeams Warm",
    "Vibrant Colors Blend",
    "Lush Green Canopies",
    "Glittering Gems Shine",
    "Icy Cliffs Tower High",
    "Whimsical Woodland Walks",
    "Tranquil Lakes Reflect",
    "Midnight Skies Unfold",
    "Freshly Cut Grass Smells",
    "Soft Petals Bloom",
    "Starry Nights Shimmer",
    "Golden Memories Glow",
    "Vibrant Markets Thrive",
    "Sparkling Fountains Dance",
    "Ocean Breezes Carry",
    "Colorful Parrots Sing",
    "Gentle Whispers Soothe",
    "Midnight Feasts Unwind",
    "Lavender Fields Sway",
    "Glowing Embers Warm",
    "Icy Mornings Chill",
    "Freshly Cut Flowers Bloom",
    "Whimsical Clocks Tick",
    "Tranquil Forests Hide",
    "Morning Chirps Rise",
    "Ocean Tides Flow",
    "Golden Light Shines",
    "Sparkling Diamonds Glitter",
    "Vibrant Rainbows Stretch",
    "Silent Nights Fall",
    "Majestic Mountains Stand",
    "Moonlit Walks Shine",
    "Lush Canopies Grow",
    "Freshly Picked Fruits Ripen",
    "Whimsical Dreams Unfold",
    "Soft Blankets Enfold",
    "Crystal Caves Reflect",
    "Glowing Lamps Light",
    "Morning Dew Refreshes",
    "Golden Sunbeams Rise",
    "Icy Cliffs Pierce High",
    "Starry Showers Fall",
    "Colorful Skies Expand",
    "Vibrant Fountains Flow",
    "Tranquil Lakes Calm",
    "Midnight Feasts Endure",
    "Freshly Cut Grass Grows",
    "Whimsical Woodland Enchants",
    "Lavender Dreams Unfold",
    "Sparkling Pools Reflect",
    "Glittering Gems Shine",
    "Ocean Waves Crash",
    "Golden Memories Remain",
    "Vibrant Markets Thrive",
    "Soft Petals Bloom",
    "Gentle Rains Soothe",
    "Midnight Skaters Glide",
    "Lush Canopies Shelter",
    "Freshly Baked Cookies Smell",
    "Whimsical Clocks Tick",
    "Majestic Castles Stand",
    "Moonlit Dances Unfold",
    "Icy Mornings Chill",
    "Colorful Kites Fly",
    "Tranquil Forests Hide",
    "Morning Chirps Rise",
    "Ocean Breezes Carry",
    "Golden Light Shines",
    "Sparkling Diamonds Glitter",
    "Silent Libraries Whisper",
    "Vibrant Rainbows Stretch",
    "Midnight Skies Unfold",
    "Freshly Cut Flowers Bloom",
    "Whimsical Toys Play",
    "Lush Green Canopies Grow",
    "Lavender Fields Sway",
    "Gentle Rains Refresh",
    "Glowing Embers Warm",
    "Icy Cliffs Pierce High",
    "Starry Showers Fall",
    "Colorful Skies Expand",
    "Vibrant Fountains Flow",
    "Tranquil Lakes Calm",
    "Midnight Feasts Endure",
    "Freshly Cut Grass Grows",
    "Whimsical Woodland Enchants",
    "Soft Petals Bloom",
    "Sparkling Pools Reflect",
    "Glittering Gems Shine",
    "Ocean Waves Crash",
    "Golden Memories Remain",
    "Vibrant Markets Thrive",
    "Gentle Whispers Soothe",
    "Midnight Skaters Glide",
    "Lush Canopies Shelter",
    "Freshly Baked Cookies Smell",
    "Whimsical Clocks Tick",
    "Majestic Castles Stand",
    "Moonlit Dances Unfold",
    "Icy Mornings Chill",
    "Colorful Kites Fly",
    "Tranquil Forests Hide",
    "Morning Chirps Rise",
    "Ocean Breezes Carry",
    "Golden Light Shines",
    "Sparkling Diamonds Glitter",
    "Silent Libraries Whisper",
    "Vibrant Rainbows Stretch",
    "Midnight Skies Unfold",
    "Freshly Cut Flowers Bloom",
    "Whimsical Toys Play",
    "Lush Green Canopies Grow",
    "Lavender Fields Sway",
    "Gentle Rains Refresh",
    "Glowing Embers Warm",
    "Icy Cliffs Pierce High",
    "Starry Showers Fall",
    "Colorful Skies Expand",
    "Vibrant Fountains Flow",
    "Tranquil Lakes Calm",
    "Midnight Feasts Endure",
    "Freshly Cut Grass Grows",
    "Whimsical Woodland Enchants",
    "Soft Petals Bloom",
    "Sparkling Pools Reflect",
    "Glittering Gems Shine",
    "Ocean Waves Crash",
    "Golden Memories Remain",
    "Vibrant Markets Thrive",
    "Gentle Whispers Soothe",
    "Midnight Skaters Glide",
    "Lush Canopies Shelter",
    "Freshly Baked Cookies Smell",
    "Whimsical Clocks Tick",
    "Majestic Castles Stand",
    "Moonlit Dances Unfold",
    "Icy Mornings Chill",
    "Colorful Kites Fly",
    "Tranquil Forests Hide",
    "Morning Chirps Rise",
    "Ocean Breezes Carry",
    "Golden Light Shines",
    "Sparkling Diamonds Glitter",
    "Silent Libraries Whisper",
    "Vibrant Rainbows Stretch",
    "Midnight Skies Unfold",
    "Freshly Cut Flowers Bloom",
    "Whimsical Toys Play",
    "Lush Green Canopies Grow",
    "Lavender Fields Sway",
    "Gentle Rains Refresh",
    "Glowing Embers Warm",
    "Icy Cliffs Pierce High",
    "Starry Showers Fall",
    "Colorful Skies Expand",
    "Vibrant Fountains Flow",
    "Tranquil Lakes Calm",
    "Midnight Feasts Endure",
    "Freshly Cut Grass Grows",
    "Whimsical Woodland Enchants",
    "Soft Petals Bloom",
    "Sparkling Pools Reflect",
    "Glittering Gems Shine",
    "Ocean Waves Crash",
    "Golden Memories Remain",
    "Vibrant Markets Thrive",
    "Gentle Whispers Soothe",
    "Midnight Skaters Glide",
    "Lush Canopies Shelter",
    "Freshly Baked Cookies Smell",
    "Whimsical Clocks Tick",
    "Majestic Castles Stand",
    "Moonlit Dances Unfold",
    "Icy Mornings Chill",
    "Colorful Kites Fly",
    "Tranquil Forests Hide",
    "Morning Chirps Rise",
    "Ocean Breezes Carry",
    "Golden Light Shines",
    "Sparkling Diamonds Glitter",
    "Silent Libraries Whisper",
    "Vibrant Rainbows Stretch",
    "Midnight Skies Unfold",
    "Freshly Cut Flowers Bloom",
    "Whimsical Toys Play",
    "Lush Green Canopies Grow",
    "Lavender Fields Sway",
    "Gentle Rains Refresh",
    "Glowing Embers Warm",
    "Icy Cliffs Pierce High",
    "Starry Showers Fall",
    "Colorful Skies Expand",
    "Vibrant Fountains Flow",
    "Tranquil Lakes Calm",
    "Midnight Feasts Endure",
    "Freshly Cut Grass Grows",
    "Whimsical Woodland Enchants",
    "Soft Petals Bloom",
    "Sparkling Pools Reflect",
    "Glittering Gems Shine",
    "Ocean Waves Crash",
    "Golden Memories Remain",
    "Vibrant Markets Thrive",
    "Gentle Whispers Soothe",
    "Midnight Skaters Glide",
    "Lush Canopies Shelter",
    "Freshly Baked Cookies Smell",
    "Whimsical Clocks Tick",
    "Majestic Castles Stand",
    "Moonlit Dances Unfold",
    "Icy Mornings Chill",
    "Colorful Kites Fly",
    "Tranquil Forests Hide",
    "Morning Chirps Rise",
    "Ocean Breezes Carry",
    "Golden Light Shines",
    "Sparkling Diamonds Glitter",
    "Silent Libraries Whisper",
    "Vibrant Rainbows Stretch",
    "Midnight Skies Unfold",
    "Freshly Cut Flowers Bloom",
    "Whimsical Toys Play",
    "Lush Green Canopies Grow",
    "Lavender Fields Sway",
    "Gentle Rains Refresh",
    "Glowing Embers Warm",
    "Icy Cliffs Pierce High",
    "Starry Showers Fall",
    "Colorful Skies Expand",
    "Vibrant Fountains Flow",
    "Tranquil Lakes Calm",
    "Midnight Feasts Endure",
    "Freshly Cut Grass Grows",
    "Whimsical Woodland Enchants",
    "Soft Petals Bloom",
    "Sparkling Pools Reflect",
    "Glittering Gems Shine",
    "Ocean Waves Crash",
    "Golden Memories Remain",
    "Vibrant Markets Thrive",
    "Gentle Whispers Soothe",
    "Midnight Skaters Glide",
    "Lush Canopies Shelter",
    "Freshly Baked Cookies Smell",
    "Whimsical Clocks Tick",
    "Majestic Castles Stand",
    "Moonlit Dances Unfold",
    "Icy Mornings Chill",
    "Colorful Kites Fly",
    "Tranquil Forests Hide",
    "Morning Chirps Rise",
    "Ocean Breezes Carry",
    "Golden Light Shines",
    "Sparkling Diamonds Glitter",
    "Silent Libraries Whisper",
    "Vibrant Rainbows Stretch",
    "Midnight Skies Unfold",
    "Freshly Cut Flowers Bloom",
    "Whimsical Toys Play",
    "Lush Green Canopies Grow",
    "Lavender Fields Sway",
    "Gentle Rains Refresh",
    "Glowing Embers Warm",
    "Icy Cliffs Pierce High",
    "Starry Showers Fall",
    "Colorful Skies Expand",
    "Vibrant Fountains Flow",
    "Tranquil Lakes Calm",
    "Midnight Feasts Endure",
    "Freshly Cut Grass Grows",
    "Whimsical Woodland Enchants",
    "Soft Petals Bloom",
    "Sparkling Pools Reflect",
    "Glittering Gems Shine",
    "Ocean Waves Crash",
    "Golden Memories Remain",
    "Vibrant Markets Thrive",
    "Gentle Whispers Soothe",
    "Midnight Skaters Glide",
    "Lush Canopies Shelter",
    "Freshly Baked Cookies Smell",
    "Whimsical Clocks Tick",
    "Majestic Castles Stand",
];

class Command {
    constructor() {
        this.name = "isapaime27ae32222";
        this.description = "its self explanatory";
        this.attributes = {
            unlisted: false,
            permission: 0,
        };
    }

    invoke(message) {
        const day = getDay365();
        const index = day % items.length;
        const item = items[index];

        const randNum = Math.round(((((46.7654897 * (day / 0.665293529972)) / 0.1687493275007) % 4) / 4) * 10000);
        message.reply({
            content: `the most AMAZING thing ever of the day is **${item}** and i like **${randNum}** today`,
            allowedMentions: {
                parse: [],
                users: [],
                roles: [],
                repliedUser: true
            }
        });
    }
}

// needs to do new Command() in index.js because typing static every time STINKS!
module.exports = Command;