const StammerImage = require("../../util/stammer-image");

const makePng = require('../../util/make-png');
const isCompatibleImage = require('../../util/compatible-images');

class Command {
    constructor() {
        this.name = "stammerimage";
        this.description = "remap the colors from first to second";
        this.attributes = {
            permission: 4,
            lockedToCommands: true,
            unlisted: true,
        };

        this.alias = ["imagestammer", "istammer", "stammeri"];
    }

    async invoke(message, args, util) {
        const [buffer1, buffer2] = await util.getInputImagesForCommand(message, 2, false, false);
        if (!buffer1) return message.reply("Add a valid image to take the colors from");
        if (!buffer2) return message.reply("Add a valid image to cover the colors onto");

        // TODO: nvm revert the thing where i removed the ETA system because some combinations still cause huge lag
        const result = await StammerImage.remap(buffer1, buffer2);
        message.reply({
            content: `Generated by <@${message.author.id}>`,
            files: [result]
        });
    }
}

// needs to do new Command() in index.js because typing static every time STINKS!
module.exports = Command;