const discord = require("discord.js");
const TTS = require("../../util/tts");

class Command {
    constructor() {
        this.name = "tts";
        this.description = "google text too specahj";
        this.attributes = {
            permission: 0,
            lockedToCommands: false,
            unlisted: false,
        };

        this.alias = ["gtts", "ttsg", "googletts", "ttsgoogle", "speak", "gspeak", "speakg", "googlespeak", "speakgoogle"];
    }

    async invoke(message, args, util) {
        const speakText = args.join(" ");
        const buffer = await TTS.speak(speakText);
        const attachment = new discord.MessageAttachment(buffer, "speech.mp3");

        message.reply({
            content: `Generated by <@${message.author.id}>`,
            files: [attachment]
        });
    }
}

// needs to do new Command() in index.js because typing static every time STINKS!
module.exports = Command;